import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Web3OnboardProviderClient} from './utils/web3OnboardProvider';
import Navbar from "./components/Navbar";
import { SelectedMomentsProvider } from "./components/SelectedMomentsProvider";
import SelectedMoments from "./components/SelectedMoments";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-US" className="container">
      <Web3OnboardProviderClient>
        <SelectedMomentsProvider>
          <body className={inter.className}>
            <SelectedMoments/>
            <Navbar/>
            {children}
          </body>
        </SelectedMomentsProvider>
      </Web3OnboardProviderClient>
    </html>
  );
}
