import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Web3OnboardProviderClient} from './utils/web3OnboardProvider';
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="container">
      <Web3OnboardProviderClient>
        <body className={inter.className}>
          <Navbar/>
          {children}
        </body>
      </Web3OnboardProviderClient>
    </html>
  );
}
