/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  CreateAchievementsPayload: CreateAchievementsPayload;
  GameplayInfo: GameplayInfo;
  GameplaysOutput: GameplaysOutput;
  ReplayAchievements: ReplayAchievements;
  GameplayPayload: GameplayPayload;
  GameplaysPayload: GameplaysPayload;
  AcquiredAchievement: AcquiredAchievement;
}
export interface CreateAchievementsPayload {
  cartridge_id: string;
  name: string;
  description: string;
  expression: string;
  icon: string;
  outcard_hash: string;
  args: string;
  in_card: string;
  log: string;
}
export interface GameplayInfo {
  id: string;
  cartridge_id: string;
  user_address: string;
  timestamp: number;
  share_value: number;
  total_shares?: number;
  achievements?: UserAchievementInfo[];
  moments?: MomentInfo[];
}
export interface UserAchievementInfo {
  user_address: string;
  timestamp: number;
  frame: number;
  index: number;
  achievement_id?: string;
  achievement_name?: string;
  achievement_description?: string;
  achievement_icon?: string;
}
export interface MomentInfo {
  id: string;
  user_address: string;
  timestamp: number;
  frame: number;
  shares: number;
}
export interface GameplaysOutput {
  data: GameplayInfo[];
  total: number;
  page: number;
}
export interface ReplayAchievements {
  cartridge_id: string;
  outcard_hash: string;
  args: string;
  in_card: string;
  log: string;
  achievements: string[];
}
export interface GameplayPayload {
  id: string;
}
export interface GameplaysPayload {
  cartridge_id?: string;
  user_address?: string;
  order_by?: string;
  order_dir?: string;
  page?: number;
  page_size?: number;
}
export interface AcquiredAchievement {
  cartridge_id: string;
  user_address: string;
  achievement_id: string;
  gameplay_id: string;
  timestamp: number;
  frame: number;
  index: number;
  cid?: string;
}
