/* eslint-disable */
/**
 * This file was automatically generated by cartesapp.template_generator.
 * DO NOT MODIFY IT BY HAND. Instead, run the generator,
 */
import { ethers, Signer, ContractReceipt } from "ethers";

import { 
    advanceInput, inspect, 
    AdvanceOutput, InspectOptions, AdvanceInputOptions, GraphqlOptions,
    EtherDepositOptions, ERC20DepositOptions, ERC721DepositOptions,
    Report as CartesiReport, Notice as CartesiNotice, Voucher as CartesiVoucher, 
    advanceDAppRelay, advanceERC20Deposit, advanceERC721Deposit, advanceEtherDeposit,
    queryNotice, queryReport, queryVoucher
} from "cartesi-client";


import Ajv from "ajv"
import addFormats from "ajv-formats"

import { 
    genericAdvanceInput, genericInspect, IOType, Models,
    IOData, Output, Event, ContractCall, InspectReport, 
    MutationOptions, QueryOptions, 
    CONVENTIONAL_TYPES, decodeToConventionalTypes
} from "../cartesapp/utils"

import * as ifaces from "./ifaces";


/**
 * Configs
 */

const ajv = new Ajv();
addFormats(ajv);
ajv.addFormat("biginteger", (data) => {
    const dataTovalidate = data.startsWith('-') ? data.substring(1) : data;
    return ethers.utils.isHexString(dataTovalidate) && dataTovalidate.length % 2 == 0;
});
const MAX_SPLITTABLE_OUTPUT_SIZE = 4194247;

/*
 * Mutations/Advances
 */

export async function achievementsReplay(
    client:Signer,
    dappAddress:string,
    inputData: ifaces.ReplayAchievements,
    options?:MutationOptions
):Promise<AdvanceOutput|ContractReceipt|any[]> {
    const data: ReplayAchievements = new ReplayAchievements(inputData);
    return genericAdvanceInput<ifaces.ReplayAchievements>(client,dappAddress,'0xbaacf812',data, options);
}

export async function createAchievement(
    client:Signer,
    dappAddress:string,
    inputData: ifaces.CreateAchievementsPayload,
    options?:MutationOptions
):Promise<AdvanceOutput|ContractReceipt|any[]> {
    const data: CreateAchievementsPayload = new CreateAchievementsPayload(inputData);
    return genericAdvanceInput<ifaces.CreateAchievementsPayload>(client,dappAddress,'0x3e0e5ffa',data, options);
}


/*
 * Queries/Inspects
 */

export async function gameplays(
    inputData: ifaces.GameplaysPayload,
    options?:QueryOptions
):Promise<InspectReport|any> {
    const route = 'achievements/gameplays';
    const data: GameplaysPayload = new GameplaysPayload(inputData);
    const output: InspectReport = await genericInspect<ifaces.GameplaysPayload>(data,route,options);
    if (options?.decode) { return decodeToModel(output,options.decodeModel || "json"); }
    return output;
}

export async function gameplayInfo(
    inputData: ifaces.GameplayPayload,
    options?:QueryOptions
):Promise<InspectReport|any> {
    const route = 'achievements/gameplay_info';
    const data: GameplayPayload = new GameplayPayload(inputData);
    const output: InspectReport = await genericInspect<ifaces.GameplayPayload>(data,route,options);
    if (options?.decode) { return decodeToModel(output,options.decodeModel || "json"); }
    return output;
}




/**
 * Models Decoders/Exporters
 */

export function decodeToModel(data: CartesiReport | CartesiNotice | CartesiVoucher | InspectReport, modelName: string): any {
    if (modelName == undefined)
        throw new Error("undefined model");
    if (CONVENTIONAL_TYPES.includes(modelName))
        return decodeToConventionalTypes(data.payload,modelName);
    const decoder = models[modelName].decoder;
    if (decoder == undefined)
        throw new Error("undefined decoder");
    return decoder(data);
}

export function exportToModel(data: any, modelName: string): string {
    const exporter = models[modelName].exporter;
    if (exporter == undefined)
        throw new Error("undefined exporter");
    return exporter(data);
}

export class ReplayAchievements extends IOData<ifaces.ReplayAchievements> { constructor(data: ifaces.ReplayAchievements, validate: boolean = true) { super(models['ReplayAchievements'],data,validate); } }
export function exportToReplayAchievements(data: ifaces.ReplayAchievements): string {
    const dataToExport: ReplayAchievements = new ReplayAchievements(data);
    return dataToExport.export();
}

export class CreateAchievementsPayload extends IOData<ifaces.CreateAchievementsPayload> { constructor(data: ifaces.CreateAchievementsPayload, validate: boolean = true) { super(models['CreateAchievementsPayload'],data,validate); } }
export function exportToCreateAchievementsPayload(data: ifaces.CreateAchievementsPayload): string {
    const dataToExport: CreateAchievementsPayload = new CreateAchievementsPayload(data);
    return dataToExport.export();
}

export class GameplayPayload extends IOData<ifaces.GameplayPayload> { constructor(data: ifaces.GameplayPayload, validate: boolean = true) { super(models['GameplayPayload'],data,validate); } }
export function exportToGameplayPayload(data: ifaces.GameplayPayload): string {
    const dataToExport: GameplayPayload = new GameplayPayload(data);
    return dataToExport.export();
}

export class GameplaysPayload extends IOData<ifaces.GameplaysPayload> { constructor(data: ifaces.GameplaysPayload, validate: boolean = true) { super(models['GameplaysPayload'],data,validate); } }
export function exportToGameplaysPayload(data: ifaces.GameplaysPayload): string {
    const dataToExport: GameplaysPayload = new GameplaysPayload(data);
    return dataToExport.export();
}

export class GameplayInfo extends Output<ifaces.GameplayInfo> { constructor(output: CartesiReport | InspectReport) { super(models['GameplayInfo'],output); } }
export function decodeToGameplayInfo(output: CartesiReport | CartesiNotice | CartesiVoucher | InspectReport): GameplayInfo {
    return new GameplayInfo(output as CartesiReport);
}

export class GameplaysOutput extends Output<ifaces.GameplaysOutput> { constructor(output: CartesiReport | InspectReport) { super(models['GameplaysOutput'],output); } }
export function decodeToGameplaysOutput(output: CartesiReport | CartesiNotice | CartesiVoucher | InspectReport): GameplaysOutput {
    return new GameplaysOutput(output as CartesiReport);
}

export class AcquiredAchievement extends Event<ifaces.AcquiredAchievement> { constructor(output: CartesiNotice) { super(models['AcquiredAchievement'],output); } }
export function decodeToAcquiredAchievement(output: CartesiReport | CartesiNotice | CartesiVoucher | InspectReport): AcquiredAchievement {
    return new AcquiredAchievement(output as CartesiNotice);
}


/**
 * Model
 */

export const models: Models = {
    'ReplayAchievements': {
        ioType:IOType.mutationPayload,
        abiTypes:['bytes32', 'bytes32', 'string', 'bytes', 'bytes', 'bytes32[]'],
        params:['cartridge_id', 'outcard_hash', 'args', 'in_card', 'log', 'achievements'],
        exporter: exportToReplayAchievements,
        validator: ajv.compile<ifaces.ReplayAchievements>(JSON.parse('{"title": "ReplayAchievements", "type": "object", "properties": {"cartridge_id": {"type": "string", "format": "binary"}, "outcard_hash": {"type": "string", "format": "binary"}, "args": {"type": "string"}, "in_card": {"type": "string", "format": "binary"}, "log": {"type": "string", "format": "binary"}, "achievements": {"type": "array", "items": {"type": "string", "format": "binary"}}}, "required": ["cartridge_id", "outcard_hash", "args", "in_card", "log", "achievements"]}'))
    },
    'CreateAchievementsPayload': {
        ioType:IOType.mutationPayload,
        abiTypes:['bytes32', 'string', 'string', 'string', 'bytes', 'bytes32', 'string', 'bytes', 'bytes'],
        params:['cartridge_id', 'name', 'description', 'expression', 'icon', 'outcard_hash', 'args', 'in_card', 'log'],
        exporter: exportToCreateAchievementsPayload,
        validator: ajv.compile<ifaces.CreateAchievementsPayload>(JSON.parse('{"title": "CreateAchievementsPayload", "type": "object", "properties": {"cartridge_id": {"type": "string", "format": "binary"}, "name": {"type": "string"}, "description": {"type": "string"}, "expression": {"type": "string"}, "icon": {"type": "string", "format": "binary"}, "outcard_hash": {"type": "string", "format": "binary"}, "args": {"type": "string"}, "in_card": {"type": "string", "format": "binary"}, "log": {"type": "string", "format": "binary"}}, "required": ["cartridge_id", "name", "description", "expression", "icon", "outcard_hash", "args", "in_card", "log"]}'))
    },
    'GameplayPayload': {
        ioType:IOType.queryPayload,
        abiTypes:[],
        params:['id'],
        exporter: exportToGameplayPayload,
        validator: ajv.compile<ifaces.GameplayPayload>(JSON.parse('{"title": "GameplayPayload", "type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}'))
    },
    'GameplaysPayload': {
        ioType:IOType.queryPayload,
        abiTypes:[],
        params:['cartridge_id', 'user_address', 'order_by', 'order_dir', 'page', 'page_size'],
        exporter: exportToGameplaysPayload,
        validator: ajv.compile<ifaces.GameplaysPayload>(JSON.parse('{"title": "GameplaysPayload", "type": "object", "properties": {"cartridge_id": {"type": "string"}, "user_address": {"type": "string"}, "order_by": {"type": "string"}, "order_dir": {"type": "string"}, "page": {"type": "integer"}, "page_size": {"type": "integer"}}}'))
    },
    'GameplayInfo': {
        ioType:IOType.report,
        abiTypes:[],
        params:['id', 'cartridge_id', 'user_address', 'timestamp', 'share_value', 'total_shares', 'achievements', 'moments'],
        decoder: decodeToGameplayInfo,
        validator: ajv.compile<ifaces.GameplayInfo>(JSON.parse('{"title": "GameplayInfo", "type": "object", "properties": {"id": {"type": "string"}, "cartridge_id": {"type": "string"}, "user_address": {"type": "string"}, "timestamp": {"type": "integer"}, "share_value": {"type": "integer"}, "total_shares": {"type": "integer"}, "achievements": {"type": "array", "items": {"$ref": "#/definitions/UserAchievementInfo"}}, "moments": {"type": "array", "items": {"$ref": "#/definitions/MomentInfo"}}}, "required": ["id", "cartridge_id", "user_address", "timestamp", "share_value"], "definitions": {"UserAchievementInfo": {"title": "UserAchievementInfo", "type": "object", "properties": {"user_address": {"type": "string"}, "timestamp": {"type": "integer"}, "frame": {"type": "integer"}, "index": {"type": "integer"}, "achievement_id": {"type": "string"}, "achievement_name": {"type": "string"}, "achievement_description": {"type": "string"}, "achievement_icon": {"type": "string"}}, "required": ["user_address", "timestamp", "frame", "index"]}, "MomentInfo": {"title": "MomentInfo", "type": "object", "properties": {"id": {"type": "string"}, "user_address": {"type": "string"}, "timestamp": {"type": "integer"}, "frame": {"type": "integer"}, "shares": {"type": "integer"}}, "required": ["id", "user_address", "timestamp", "frame", "shares"]}}}'))
    },
    'GameplaysOutput': {
        ioType:IOType.report,
        abiTypes:[],
        params:['data', 'total', 'page'],
        decoder: decodeToGameplaysOutput,
        validator: ajv.compile<ifaces.GameplaysOutput>(JSON.parse('{"title": "GameplaysOutput", "type": "object", "properties": {"data": {"type": "array", "items": {"$ref": "#/definitions/GameplayInfo"}}, "total": {"type": "integer"}, "page": {"type": "integer"}}, "required": ["data", "total", "page"], "definitions": {"UserAchievementInfo": {"title": "UserAchievementInfo", "type": "object", "properties": {"user_address": {"type": "string"}, "timestamp": {"type": "integer"}, "frame": {"type": "integer"}, "index": {"type": "integer"}, "achievement_id": {"type": "string"}, "achievement_name": {"type": "string"}, "achievement_description": {"type": "string"}, "achievement_icon": {"type": "string"}}, "required": ["user_address", "timestamp", "frame", "index"]}, "MomentInfo": {"title": "MomentInfo", "type": "object", "properties": {"id": {"type": "string"}, "user_address": {"type": "string"}, "timestamp": {"type": "integer"}, "frame": {"type": "integer"}, "shares": {"type": "integer"}}, "required": ["id", "user_address", "timestamp", "frame", "shares"]}, "GameplayInfo": {"title": "GameplayInfo", "type": "object", "properties": {"id": {"type": "string"}, "cartridge_id": {"type": "string"}, "user_address": {"type": "string"}, "timestamp": {"type": "integer"}, "share_value": {"type": "integer"}, "total_shares": {"type": "integer"}, "achievements": {"type": "array", "items": {"$ref": "#/definitions/UserAchievementInfo"}}, "moments": {"type": "array", "items": {"$ref": "#/definitions/MomentInfo"}}}, "required": ["id", "cartridge_id", "user_address", "timestamp", "share_value"]}}}'))
    },
    'AcquiredAchievement': {
        ioType:IOType.notice,
        abiTypes:['bytes32', 'address', 'bytes32', 'bytes32', 'uint', 'uint', 'uint', 'string'],
        params:['cartridge_id', 'user_address', 'achievement_id', 'gameplay_id', 'timestamp', 'frame', 'index', 'cid'],
        decoder: decodeToAcquiredAchievement,
        validator: ajv.compile<ifaces.AcquiredAchievement>(JSON.parse('{"title": "AcquiredAchievement", "type": "object", "properties": {"cartridge_id": {"type": "string", "format": "binary"}, "user_address": {"type": "string"}, "achievement_id": {"type": "string", "format": "binary"}, "gameplay_id": {"type": "string", "format": "binary"}, "timestamp": {"type": "integer"}, "frame": {"type": "integer"}, "index": {"type": "integer"}, "cid": {"default": "", "type": "string"}}, "required": ["cartridge_id", "user_address", "achievement_id", "gameplay_id", "timestamp", "frame", "index"]}'.replaceAll('integer','string","format":"biginteger')))
    },
    };